services:
  memgraph:
    image: memgraph/memgraph-platform:${MEMGRAPH_VERSION}
    ports:
      - ${MEMGRAPH_BOLT_PORT}:7687
      - 7444:7444
      - 3000:3000
    environment:
      - MEMGRAPH=--bolt-server-name-for-init=Neo4j/ --telemetry-enabled=false --storage-properties-on-edges=true
    healthcheck:
      test: nc -zw 1 localhost 7687
      interval: 5s
      timeout: 30s
      retries: 5
    volumes:
#      - ./data/memgraph/mg_lib:/var/lib/memgraph
#      - ./data/memgraph/mg_log:/var/log/memgraph
#      - ./data/memgraph/mg_etc:/etc/memgraph
      - ./datasets/pole:/datasets/pole
    entrypoint: ["/usr/bin/supervisord"]
