services:
  neo4j5:
    image: neo4j:${NEO4J_VERSION}
    ports:
      - 7474:7474
      - ${NEO4J_BOLT_PORT}:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      #- NEO4J_dbms_memory_heap_max__size=4G
      #- NEO4J_dbms_connector_bolt_advertised__address=localhost:${NEO4J_BOLT_PORT}
      - NEO4JLABS_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 3s
    volumes:
      - ./data/neo4j5/data:/data
      - ./data/neo4j5/plugins:/plugins
      - ./data/neo4j5/backup:/backup
      - ./datasets/pole:/import/datasets/pole
