services:
  memgraph:
    image: memgraph/memgraph-platform:2.10.0-memgraph2.10.0-lab2.8.0-mage1.9
    ports:
      - 7687:7687
      - 3000:3000
      - 7444:7444
    environment:
      - MEMGRAPH=--bolt-server-name-for-init=Neo4j/ --telemetry-enabled=false --storage-properties-on-edges=true
#    healthcheck:
#      test: bash -c 'netstat -ltn | grep - \':7687\''
#      interval: 3s
#      timeout: 30s
    volumes:
#      - ./data/memgraph/mg_lib:/var/lib/memgraph
#      - ./data/memgraph/mg_log:/var/log/memgraph
#      - ./data/memgraph/mg_etc:/etc/memgraph
      - ./datasets/pole:/datasets/pole
    entrypoint: ["/usr/bin/supervisord"]

